global using Autofac;
global using CoffeeBackup.Common.Extensions;
global using Serilog;
global using SharpCompress.Common;
global using SharpCompress.Writers;
global using CoffeeBackup.Common.Abstract;
global using CoffeeBackup.Common.Logic;
global using Microsoft.Extensions.Configuration;
global using CoffeeBackup.Common.Models;
global using CoffeeBackup.Lib.NotificationProviders;
global using SendGrid;
global using SendGrid.Helpers.Mail;
global using System.Text;
global using static CoffeeBackup.Common.Data.Enums;