version: '3.8'

services:
  coffeebackup:
    container_name: coffeebackup
    restart: unless-stopped
    image: ${DOCKER_REGISTRY-}coffeebackup-debug
    build: # change to dockerhub version
      context: .
      dockerfile: Dockerfile
    volumes:
    # -- Application volumes (Leave these)
    - /etc/coffeebackup/appsettings.json:/app/appsettings.json
    - /var/log/coffeebackup/:/app/logs/

    # -- Backup Volumes
    # All paths that require backup should be defined here
    # In linux, the backup mount point is `/backup/`
    - /etc/nginx/sites-enabled/:/backup/etc/nginx/sites-enabled:ro
    - /home/myusername:/backup/home/myusername:ro
    - /home/anotheruser/specificfile.txt:/backup/home/myusername/specificfile.txt:ro