global using CoffeeBackup.Service;
global using System.Reflection;
global using Autofac;
global using Autofac.Extensions.DependencyInjection;
global using CoffeeBackup.Common;
global using Serilog;
global using ILogger = Serilog.ILogger;
global using CoffeeBackup.Lib;
global using CoffeeBackup.Common.Abstract;
global using CoffeeBackup.Common.Logic;
global using CoffeeBackup.StorageProviders;
global using CoffeeBackup.Service.Workers;
global using CoffeeBackup.StorageProviders.AmazonS3;
global using CoffeeBackup.StorageProviders.Storj;